from libem.core.struct import Prompt

query = Prompt(
    default="Do the two product descriptions refer to the same real-world product? "
            "Answer with 'Yes' if they do and 'No' if they do not.\n"
            "Entity 1: {left}.\nEntity 2: {right}.",
    options=[""],
)

rule = Prompt(
    default="",
    
    # AMAZON GOOGLE:
    # 'Mistakes to avoid:\n'
    # '- Consider version and edition differences explicitly, even if titles are similar.\n'
    # '- Check for specific product types like upgrades, licenses, or bundles, and do not assume they are the same as standalone products.\n'
    # '- Validate that the product intended for the same platform (e.g., Windows, Mac) before matching.\n'
    # '- Ensure that the product titles match closely, avoiding mismatches due to additional descriptors that change the product context (e.g., family pack, professional edition).\n'
    # '- Do not match products based solely on the presence of similar keywords; context and completeness of the title are crucial.\n'
    # '- Compare manufacturer names if available; absence in one entity does not immediately imply a match with an entity having a manufacturer.\n'
    # '- Price differences can be indicative of different products or versions; significant price discrepancies likely mean different products.\n'
    # '- Consider the release context, such as software version numbers or edition years, to ensure both products are indeed the same.\n'
    # '- Avoid matching products where one is a specific type of service or subscription unless explicitly stated in both entities.\n'
    # '- Be cautious with products that have similar names but may differ in content or intended use, such as educational versions versus professional versions.\n'
    # '- Acknowledge the presence of additional terms like "deluxe," "premium," or "professional" as they typically denote different product tiers.\n'
    # '- Do not assume products are the same based on partial title matches; ensure all major elements of the product title align.\n'
    # '- For software, consider the implications of different licensing terms or durations mentioned in the titles.\n'
    # '- When in doubt, err on the side of not matching unless all key aspects (title, manufacturer, version, price) align closely.\n',
    
    # WALMART AMAZON:
    # 'Mistakes to avoid:\n'
    # '- Check for exact match in model numbers when available; if they differ, entities are likely not the same.  \n'
    # '- Consider the product category; if categories are vastly different, the entities are likely not the same.  \n'
    # '- Verify the number of items or features listed in the title; a mismatch suggests different entities.  \n'
    # '- For products with potentially multiple versions or colors, treat them as different unless explicitly stated otherwise.  \n'
    # '- Ensure consistency in product descriptions; significant differences in features or specifications indicate different entities.  \n'
    # '- Price differences can be a clue, but should not be the sole criterion for matching, especially in different stores or regions.  \n'
    # '- For entities without model numbers, closely analyze the title and description for matching key features.  \n'
    # '- When in doubt about partial information (e.g., missing brand or model number), seek additional attributes to confirm a match.  \n'
    # '- Always consider the context and intended use of the product; similar sounding items might be used differently.  \n'
    # '- For entities with ambiguous or incomplete data, prioritize conservative matching to avoid false positives.  \n',
    
    # DBLP-ACM
    # 'Mistakes to avoid:\n'
    # '- Consider variations in venue names as distinct unless explicitly known to be the same.  \n'
    # '- Treat minor title variations as potentially different entities.  \n'
    # '- Account for differences in author name order as indicative of different contributions or roles.  \n'
    # '- Do not assume identical years imply the same publication; context matters.  \n'
    # '- Verify the full context of publication types (e.g., demo abstract vs. full paper) before matching.  \n'
    # '- Cross-check additional metadata like page numbers or DOI for further verification when available.  \n'
    # '- Use caution with special characters and encoding differences in author names.  \n'
    # '- Incorporate external sources or databases for normalization of venue names and author identities.  \n'
    # '- Develop a scoring system for similarity '
    # 'that includes weighted factors like '
    # 'title, author list, venue, and year.  \n'
    # '- Implement a threshold for similarity '
    # 'scores below which entities are not '
    # 'considered matches.Mistakes to avoid:\n'
    # '- Consider differences in publication '
    # 'years as a strong indicator of '
    # 'non-matching entities, even if other '
    # 'attributes are similar.\n'
    # '- \n'
    # '- Evaluate the similarity of venue names '
    # 'carefully, recognizing that different '
    # 'names may refer to different conferences '
    # 'or journals.\n'
    # '- \n'
    # '- Do not assume two entities are the same '
    # 'based solely on title similarity; '
    # 'consider variations in titles that might '
    # 'indicate different content or focus.\n'
    # '- \n'
    # '- Check the order and presence of all '
    # 'authors; a mismatch in author order or '
    # 'missing authors can indicate different '
    # 'publications.\n'
    # '- \n'
    # '- Be cautious with titles that have added '
    # 'or altered phrases, as these can change '
    # 'the scope or contribution of the work.\n'
    # '- \n'
    # '- Always consider the context and '
    # 'specificity of the venue, especially when '
    # 'dealing with abbreviations or acronyms '
    # 'that might be used for different venues.\n'
    # '- \n'
    # '- Use a combination of all available '
    # 'attributes (authors, title, venue, year) '
    # 'rather than relying heavily on one single '
    # 'attribute for matching decisions.',
    
    
    # GPT-3.5-TURBO AMAZON-GOOGLE
    # 'Mistakes to avoid:\n'
                                    # '- Match entities if titles are similar, '
                                    # 'disregarding minor differences such as '
                                    # 'punctuation, order of words, and presence '
                                    # 'of version numbers.\n'
                                    # '- \n'
                                    # '- Consider entities as matching if the '
                                    # 'manufacturer is the same or if one entity '
                                    # 'lacks a manufacturer but other details '
                                    # 'align closely.\n'
                                    # '- \n'
                                    # '- Treat entities with very close prices '
                                    # '(within a small percentage threshold) as '
                                    # 'potentially matching, especially if other '
                                    # 'details like title or manufacturer '
                                    # 'align.\n'
                                    # '- \n'
                                    # '- Do not match entities based solely on '
                                    # 'similar titles if the product versions or '
                                    # 'editions are different, particularly for '
                                    # 'software.\n'
                                    # '- \n'
                                    # '- Ignore minor price differences when '
                                    # 'other factors like title and manufacturer '
                                    # 'strongly suggest a match.\n'
                                    # '- \n'
                                    # '- Consider entities as non-matching if '
                                    # 'there is a significant price difference '
                                    # 'unless there is overwhelming evidence '
                                    # 'from other attributes (like exact title '
                                    # 'and manufacturer match).\n'
                                    # '- \n'
                                    # '- Do not assume entities are the same if '
                                    # 'one mentions a specific feature or '
                                    # 'component (like "upgrade" or "bundle") '
                                    # 'that the other does not, unless all other '
                                    # 'information matches.\n'
                                    # '- \n'
                                    # '- Entities with different primary '
                                    # 'functions or intended uses (e.g., '
                                    # 'different types of software or different '
                                    # 'editions) should not be matched, even if '
                                    # 'titles are similar.\n'
                                    # '- \n'
                                    # '- Use caution when matching entities with '
                                    # 'and without manufacturer details; ensure '
                                    # 'other attributes like title and price are '
                                    # 'very closely aligned.\n'
                                    # '- \n'
                                    # '- When in doubt, prioritize title and '
                                    # 'manufacturer similarity over price, '
                                    # 'especially for high-value items where '
                                    # 'price variations can be larger.\n'
                                    # ,
    
    # GPT-4
    # 'Mistakes to avoid:\n'
    #                                 '- Consider version compatibility and '
    #                                 'specificity when matching software '
    #                                 'titles.  \n'
    #                                 '- Ensure exact match or clear equivalence '
    #                                 'in product descriptions before confirming '
    #                                 'a match.  \n'
    #                                 '- Verify that the product type (e.g., '
    #                                 'upgrade, deluxe, standard) matches '
    #                                 'exactly between entities.  \n'
    #                                 '- Check for platform compatibility (e.g., '
    #                                 'Windows vs. Mac) in software titles.  \n'
    #                                 '- Match manufacturer names accurately, '
    #                                 'and do not assume a match when the '
    #                                 'manufacturer is unspecified in one '
    #                                 'entity.  \n'
    #                                 '- Consider the context and usage of the '
    #                                 'product (e.g., academic, professional, '
    #                                 'personal) when matching.  \n'
    #                                 '- Do not rely solely on price similarity '
    #                                 'to determine a match; significant price '
    #                                 'differences often indicate different '
    #                                 'products or packages.  \n'
    #                                 '- Be cautious with numerical versions and '
    #                                 'editions; ensure they exactly match or '
    #                                 'are contextually appropriate (e.g., '
    #                                 'version 2.0 vs. deluxe 2.0).  \n'
    #                                 '- Pay attention to licensing terms and '
    #                                 'durations (e.g., 1-year vs. 3-year '
    #                                 'licenses) as they can differentiate '
    #                                 'products.  \n'
    #                                 '- Ensure that additional descriptors like '
    #                                 '"complete package" or "media only" are '
    #                                 'considered in the matching '
    #                                 'process.\n'
                                    
    #                                 '- Consider manufacturer consistency: if '
    #                                 'one entity has a manufacturer listed and '
    #                                 'the other does not, verify other '
    #                                 'attributes closely before matching.\n'
    #                                 '- \n'
    #                                 '- Check for version or edition '
    #                                 'information in titles: products with '
    #                                 'different versions or editions (e.g., '
    #                                 '"standard" vs. "deluxe") are likely '
    #                                 'different products.\n'
    #                                 '- \n'
    #                                 '- Validate product type and usage: ensure '
    #                                 'that both entities refer to the same type '
    #                                 'of product (e.g., software vs. upgrade '
    #                                 'package).\n'
    #                                 '- \n'
    #                                 '- Price similarity is important but not '
    #                                 'definitive: small price differences can '
    #                                 'be acceptable, but very large '
    #                                 'discrepancies likely indicate different '
    #                                 'products.\n'
    #                                 '- \n'
    #                                 '- Examine completeness of product titles: '
    #                                 'missing key words or numbers in one title '
    #                                 'can indicate a different product, even if '
    #                                 'other words match.\n'
    #                                 '- \n'
    #                                 '- Consider the context of numbers and '
    #                                 'identifiers in titles: product codes or '
    #                                 'version numbers must match if present.\n'
    #                                 '- \n'
    #                                 '- Assess relevance of additional '
    #                                 'descriptors: words like "upgrade," "full '
    #                                 'package," "universal license," etc., can '
    #                                 'signify different product offerings.\n'
    #                                 '- \n'
    #                                 '- Be cautious with generic titles: titles '
    #                                 'that are too vague or lack specific '
    #                                 'details are more prone to '
    #                                 'misclassification.\n'
    #                                 '- \n'
    #                                 '- Language and regional versions matter: '
    #                                 'products targeted at different linguistic '
    #                                 'or regional markets (e.g., "Canadian '
    #                                 'French") are distinct.\n'
    #                                 '- \n'
    #                                 '- Verify product functionality or focus: '
    #                                 'differences in implied functionality '
    #                                 '(e.g., "home design" vs. "professional '
    #                                 'design") suggest different products.\n'
    #                                 '- \n'
    #                                 '- Cross-check with known databases or '
    #                                 'catalogs when possible to confirm product '
    #                                 'identity if uncertainty persists.\n'
    #                                 '- \n'
    #                                 '- Use common sense and domain knowledge: '
    #                                 'if a match seems unlikely based on '
    #                                 'general knowledge of the product or '
    #                                 'market, it probably is.',
)

experience = Prompt(
    default=Prompt.Experience(),
    options=[""],
)

output = Prompt(
    default="",
    options=["Explain your answer step by step and end with 'yes' or 'no' only."  # CoT
             "Answer only 1 or 0.",
             "Answer with 'yes' or 'no' only, in lower case.", ],
)
