apiVersion: apps/v1
kind: Deployment
metadata:
  name: libem-arena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libem-arena
  template:
    metadata:
      labels:
        app: libem-arena
    spec:
      containers:
      - name: libem-arena-app
        image: daiwaid/libem-arena-prod:latest
        ports:
          - containerPort: 5000
      - name: libem-arena-serve
        image: daiwaid/libem-arena-serve-prod:latest
        ports:
          - containerPort: 8000
        envFrom:
          - secretRef:
              name: arena-env-vars
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
   matchLabels:
     app: mysql
  template:
   metadata:
     labels:
      app: mysql
   spec:
    containers:
    - name: mysql
      image: mysql:latest
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: arena-env-vars
            key: MYSQL_ROOT_PASSWORD
      ports:
      - containerPort: 3306
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
      - name: mysql-initdb
        mountPath: /docker-entrypoint-initdb.d
    volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
    - name: mysql-initdb
      configMap:
        name: initdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
data:
  initdb.sql: |-
    CREATE DATABASE arenadb;
    CREATE USER 'mysql'@'%' IDENTIFIED BY 'password';
    GRANT CREATE, INSERT, UPDATE, DELETE, SELECT ON arenadb.* TO 'mysql'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: Service
metadata:
  name: libem-arena-service
spec:
  type: NodePort
  selector:
    app: libem-arena
  ports:
    - protocol: TCP
      name: tcp-5000
      port: 5000
      targetPort: 5000
      nodePort: 30050
    - protocol: TCP
      name: tcp-8000
      port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
