apiVersion: apps/v1
kind: Deployment
metadata:
  name: libem-web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libem-web-service
  template:
    metadata:
      labels:
        app: libem-web-service
    spec:
      containers:
      - name: libem-web-service
        image: daiwaid/libem-serve:latest
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: env-vars
---
apiVersion: v1
kind: Service
metadata:
  name: libem-web-service
spec:
  type: NodePort
  selector:
    app: libem-web-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
